"""Shared management contract for the native client-agent processes."""

CONTROL_PROTOCOL_VERSION = 1
PINGMESH_CONTROL_PORT = 9910
TRAFFIC_CONTROL_PORT = 9911
HEARTBEAT_MAX_AGE_SECONDS = 10.0

__all__ = [
    "CONTROL_PROTOCOL_VERSION",
    "HEARTBEAT_MAX_AGE_SECONDS",
    "PINGMESH_CONTROL_PORT",
    "TRAFFIC_CONTROL_PORT",
]
